sudo: false

language: node_js
node_js:
  - "14.12.0"
cache:
  directories:
    - node_modules
install:
  npm i @storybook/react@6.0.12
env:
  - CI=ture
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master
