sudo: false

language: node_js
node_js:
  - "stable"
cache:
  npm: false
env:
  - CI=ture
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master