sudo: false

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CI=ture
script:
  - npm run build-stroybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: travis-ci